
trigger:
- master

variables:
    azureSubscription: 'Visual Studio Enterprise 2'
    vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        npm install
        npm run build --if-present
        npm run test --if-present
      displayName: 'npm install, build and test'
  
    - task: CopyFiles@2
      inputs:
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
  
    - task: PublishBuildArtifacts@1
      inputs: 
        pathtoPublish: $(Build.ArtifactStagingDirectory)
    
    # - task: AzureVmssDeployment@0
    #   inputs:
    #     azureSubscription: azureSubscription
    #     #action: 'Update image' # Options: update Image, configure Application Startup
    #     vmssName: 'vmss01'
    #     vmssOsType: linux
    #     imageUrl: 
        #customScriptsDirectory: # Optional
        #customScript: # Optional
        #customScriptArguments: # Optional
        #customScriptsStorageAccount: # Optional
        #skipArchivingCustomScripts: # Optional